resources:
  - name: MyGitHub
    type: GitRepo
    configuration:
      path: RjSH1/jfrog-pipelines-extensions    # <-- Change to your repository path
      gitProvider: myGithub                                    # <-- Change to your GitHub integration

pipelines: 
  - name: npm
    steps:
      - name: buildStepName
        type: NpmBuild
        #syntaxVersion: 1.0.0
        configuration:
          #sourceArtifactory: myArtifactory
          sourceLocation: $res_MyGitHub_resourcePath
          repositoryName: npm
          #buildCommand: make # optional
          integrations:
            - name: myArtifactory
          inputResources:
            - name: myGithub
          npmArgs: "--verbose"
      - name: NpmPublish
        type: NpmPublish
        configuration:
          #sourceArtifactory: myArtifactory
          repositoryName: npm-local
          integrations:
            - name: myArtifactory
          inputSteps:
            - name: buildStepName
